### ISSUE TITLE
make agent itself as subreaper

### ISSUE THREAD

**Issue by laijs** [kata-containers/agent#23]
- [ ] A loop that calls syscall.Wait() to reap processes
     And to collect processes' exitcode
- [ ] Make itself as PR_SET_CHILD_SUBREAPER
     It is essential when the agent is not launched as the vm's init process.

**Comment by WeiZhang555** [comment]
Agree :+1:

**Comment by sboeuf** [comment]
Hey !
I have been thinking about this and I actually had not realized we needed such a thing (a subreaper) for all the children and grandchildren and grandgrand... processes that could be spawned from the container or exec processes.
I have made some testing with our agent from Clear Containers (also using libcontainer) and here is the way we should handle this:
- We set the agent as the subreaper of all the processes.
- We start a Go routine loop from the agent, waiting for ALL processes.
- We add to the `sandbox` structure a map of Go channels with processes PID being the key.
- From the PID waiting loop, if the pid of the reaped process match one of the process inside from the map, we send the exit code of this process through this channel.
- In the meantime, `WaitProcess()` will be called, and it is going to start listening on this channel from the map, awaiting for the exit code to be received.Once it gets the exit code, it calls into process.Wait() (libcontainer function), this way every thing will be cleaned up by libcontainer itself. Here is a comment from `runc` implementation to illustrate this:

> call Wait() on the process even though we already have the exit status because we must ensure that any of the go specific process fun such as flushing pipes are complete before we return.

This comes from `signals.go` in `runc`, and here we can see they don't bother testing the error returned:
```go
case unix.SIGCHLD:
	exits, err := h.reap()
	if err != nil {
		logrus.Error(err)
	}
	for _, e := range exits {
		logrus.WithFields(logrus.Fields{
			"pid":    e.pid,
			"status": e.status,
		}).Debug("process exited")
		if e.pid == pid1 {
			// call Wait() on the process even though we already have the exit
			// status because we must ensure that any of the go specific process
			// fun such as flushing pipes are complete before we return.
			process.Wait()
			if h.notifySocket != nil {
				h.notifySocket.Close()
			}
			return e.status, nil
		}
	}
```

This approach will prevent any errors related to the fact that we cannot control who is going to receive the exit code if we are waiting the same PID from 2 different Go routines at the same time. Indeed, the subreaper fixes the issue of the children and grandchildren reaping, but we didn't initially need it for the container or exec process since we know we have to wait for them. This approach centralize all the `wait()` through a unique Go routine.

I have been discussing about this with @sameo and he agrees with it.
@laijs @bergwolf @gnawux Does this make sense ?

**Comment by WeiZhang555** [comment]
> Indeed, the subreaper fixes the issue of the children and grandchildren reaping, but we didn't initially need it for the container or exec process since we know we have to wait for them. This approach centralize all the wait() through a unique Go routine.

I think that's not all the cases, IMO, we can get a list of the spawned child pid, but can't get the grand and grandgrand children pids. (Can we? correct me if wrong). The subreaper can help fix PID 1 problem of containers[1]. 

In our scenario, agent forkes container init process and exec process, 
for example, 

systemd(pid 1 in VM) -- agent --container init -- forked processes 

if "container init" isn't written appropriately, for example, a badly written go program which doesn't wait and reap its children when itself dies, or "container init" is accidentally killed without time reaping its children. then "forked processes" will be re-parented to systemd and waiting systemd to reap them, right? So if systemd didn't reap "forked processes" in time, kernel resources will be possible to be exhausted.  But if agent set itself as a subreaper, all "forked processes" will be children of "agent" after "container init" killed, and agent will wait for all processes in case resources(such as PID numbers) are exhausted too quickly.

In our scenario, all things below systemd are running inside a VM, so maybe, it's not that critical, but with subreaper we can be more confident to our own logics instead of systemd default behavior, in other hand, setting subreaper bring no harm to us IMO 😉 

[1] https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by bergwolf** [comment]
I've been playing around this a bit today and I don't think the current proposal (use a `pause` program to own the shared pid namespace and let agent handle all `SIGCHLD`, #28 #29 ) can work.

The main reason is that even though `prctl(PR_SET_CHILD_SUBREAPER)` can let a process fulfill the role of init(1) for all of its descendant processes, the situation is not kept if any descendant process joins a different pid namespace, in which case, `SIGCHLD` is sent to the pid 1 of the new namespace rather than the original subreaper process that forks the child process.

I have a test program showing result:
https://github.com/bergwolf/linux-namespace-tests#linux-namespace-playground

Therefore, the way to handle SIGCHLD and pid namespace sharing should indeed be considered together, as I commented in https://github.com/kata-containers/agent/pull/28, we should combine shared pidns support with zombie children reaper so that either:
   - the agent is pid1 of the shared pidns and handles SIGCHLD, or
   - the pause process lives is the pid1 of the shared pidns and handles SIGCHLD

**Comment by laijs** [comment]
@bergwolf Your test case is not the case for the agent or libcontainer.
If processA enter pidnsB, Non of the descendant of processA is the descendant of pidnsB.

**Comment by sboeuf** [comment]
@bergwolf I need to do some testing too. But if what you're saying is true (a subreaper don't receive SIGCHLD across PID namespaces), then how do we handle the case of a non-shared PID namespace ?

**Comment by bergwolf** [comment]
I'm changing the tests to match agent/libcontainer use case. Will update here later.

**Comment by bergwolf** [comment]
update: I was wrong. If new process is forked from outside of the pidns, it will be reparented to its subreaper ancestor, which is exactly the agent use case.

**Comment by sboeuf** [comment]
@bergwolf what about the children and grandchildren. The case we're trying to cover here is:
- We have the agent set as the subreaper
- The agent will spawn container process, and libcontainer takes care of that, making this process entering a new PID ns.
- The container process will spawn a bunch of new children and grandchildren.

The question is, do we get all the SIGCHLD (from the agent) for all the processes that I have mentioned here ?

**Comment by bergwolf** [comment]
@sboeuf in my test, yes. All SIGCHLD of agent's children/grandchildren etc. are sent to the subreaper agent no mater if they enter which pidns.

**Comment by sboeuf** [comment]
Phew ! I am relieved :)
@bergwolf then you're okay with #28 ?

**Comment by bergwolf** [comment]
@sboeuf yes, I think it is the right way to go.

**Comment by sboeuf** [comment]
@bergwolf glad to hear that :)
