### ISSUE TITLE
yamux: keepalive failed: i/o deadline reached

### ISSUE THREAD

**Issue by devimc** [kata-containers/agent#231]
# Description of problem

Run a container with -ti and pause it for 45 seconds

*Terminal 1*
```
$ docker run --name foo -ti centos bash
```

*Terminal 2*
```
$ docker pause foo
$ sleep 45
$ docker unpause foo
```

*Terminal 1* gets stuck after 45 second and next message is logged in the journal

```
[ERR] yamux: keepalive failed: i/o deadline reached
```

**Comment by grahamwhaley** [comment]
Ah, I think I have seen this recently, but not had time to track down why... currently, if you 'ignore' a container, it will stop responding and then die... good find! +1 for I think this is a real current issue!
Hmm, so we *could* add a test for this to the CI - but that would push out CI feedback loop time another 10 minutes.... so, maybe we won't ... but, if we ever get a 'long soak test' QA CI, that maybe runs on the master branch merges (rather than PRs), then we should add it there.

**Comment by grahamwhaley** [comment]
I've added a P1 label as well...

**Comment by devimc** [comment]
@sboeuf ehmm, which timeout? is there a timeout in yamux?

**Comment by sboeuf** [comment]
Take a look at this test on the yamux repo: https://github.com/hashicorp/yamux/blob/master/session_test.go#L797-L838

**Comment by WeiZhang555** [comment]
Interesting find :+1:

**Comment by jingxiaolu** [comment]
This is interesting...
I checked code, currently in `agent/channel.go`, if we use `serialChannel`, `config=nil` when calling `yamux.Server()`: https://github.com/kata-containers/agent/blob/ea0e6ae4862c8af0b2d10eb6c074682fd676016a/channel.go#L149
So yamux will use default config, which already `EnableKeepAlive`: https://github.com/kata-containers/agent/blob/ea0e6ae4862c8af0b2d10eb6c074682fd676016a/vendor/github.com/hashicorp/yamux/mux.go#L38-L47

**Comment by jingxiaolu** [comment]
Seems this is because we should update the vendor package `agent` in `shim` now. 

Now in `shim`, when it calls `NewAgentClient()`, in current vendor it's `agentDialer()`, it will not create a yamux client `func agentDialer(addr *url.URL) dialer {`:
https://github.com/kata-containers/shim/blob/2457ccc107ac46d7105254c089b240523b1701c4/vendor/github.com/kata-containers/agent/protocols/client/client.go#L115-L129

While in current `agent`'s protocol, it will return a yamux client...
https://github.com/kata-containers/agent/blob/ea0e6ae4862c8af0b2d10eb6c074682fd676016a/protocols/client/client.go#L122-L150

I might give it a try on Monday...

**Comment by jingxiaolu** [comment]
Sorry the yamux client here is `kata proxy` but not `kata shim`, so `shim` may not necessary to upgrade the vendor `agent`.

In my TE, I can't reproduce the same phenomenon by leaving it for long time. 
I can reproduce it with:
1. run a new container with kata-runtime;
2. send signal 19 `SIGSTOP` to `proxy`;
3. wait for more than 30 seconds;
4. send signal 18 `SIGCONT` to `proxy`;
5. check journal log, get the same error print

**Comment by devimc** [comment]
@jingxiaolu  thanks for debugging it, let me try to find another way to reproduce it

**Comment by devimc** [comment]
Hi I found an easy way to reproduce it

*Terminal 1*
```
$ docker run --name foo -ti centos bash
```

*Terminal 2*
```
$ docker pause foo
$ sleep 600
$ docker unpause foo
```

container get stuck in *Terminal 1*

**Comment by devimc** [comment]
actually 45 seconds is enough to reproduce this issue.
updating issue

**Comment by jshachm** [comment]
`docker pause`  finally also sends `SIGSTOP` to container process(here in `kata` is `shim` represents).
So we find a  actual `docker cli` option to reproduce it.

Good job for both of you~~~
@jingxiaolu @devimc

**Comment by devimc** [comment]
please take a look https://github.com/kata-containers/proxy/pull/71

**Comment by jshachm** [comment]
Making a mistake. Nowadays, we just support `kata-runtime pause` cli just `pause` hypervisor(vm) using `qmp` cmd. Not like what `runc`  does, change cgroup freezer for all container process.

**Comment by devimc** [comment]
see https://github.com/kata-containers/proxy/issues/70
