### ISSUE TITLE
network: Add list APIs to show the actual network info in a container

### ISSUE THREAD

**Issue by caoruidong** [kata-containers/agent#315]
According to the discussion in https://github.com/kata-containers/runtime/issues/113, two APIs are missing.
```
rpc ListInterfaces(ListInterfacesRequest) returns(Interfaces);
rpc ListRoutes(ListRoutesRequest) returns (Routes);
```
Need to implement them to support network hotplug.

And how about these two?
```
rpc AddInterface(AddInterfaceRequest) returns(Interface);
rpc RemoveInterface(RemoveInterfaceRequest) returns (Interface);
```
Delete them or keep them for compatibility？

**Comment by sboeuf** [comment]
>And how about these two?
>```
>rpc AddInterface(AddInterfaceRequest) returns(Interface);
>rpc RemoveInterface(RemoveInterfaceRequest) returns (Interface);
>```

@caoruidong are you referring to the Agent API here? I will assume that's what you're talking about and I would say that we should remove them since we're not using them internally. But I'd also say this should come in a different PR (a follow up one) once we got the network hotplug merged, just to avoid any confusion.

**Comment by caoruidong** [comment]
@sboeuf OK. Just add list APIs.
