### ISSUE TITLE
agent: get content of a file in sandbox

### ISSUE THREAD

**Issue by clarecch** [kata-containers/agent#354]
# Description of problem

In https://github.com/kata-containers/runtime/pull/624, we have such problems:
1. Hot add memory should be aligned to memory section size, but the size of a memory section is architecture dependent. For example, power uses 16MB, ia64 uses 1GB, x86_64 uses 128MB, ppc64le uses 256MB.
2. Each memory block is described under /sys/devices/system/memory as /sys/devices/system/memory/memoryXXX (XXX is the memory block id.), which is the unit of memory online/offline. In sparse memory model, memory block size is a multiple of memory section size, [reference](http://www.infradead.org/~mchehab/kernel_docs/unsorted/memory-hotplug.html#unit-of-memory-online-offline-operation). We can online a memory block only if we hotplug a memory-block-sized dimm, see `pages_correctly_reserved` in [reference](https://elixir.bootlin.com/linux/v4.14.49/source/drivers/base/memory.c#L230).

So we should get the size of guestos memory block by reading /sys/devices/system/memoryblock_size_bytes in sandbox, and make hot add memory to be aligned to memory block size of sandbox. 

I think it's needed to add a ReadSandboxFile rpc to read file above in a common way.

**Comment by jodh-intel** [comment]
As mentioned on https://github.com/kata-containers/runtime/pull/624, the ideal would be that the agent handles all the memory boundary logic rather than having to add a new gRPC call so the runtime can do the calculations.

However, if we *really* need an agent call, how about we abuse the `CheckRequest()` call?

- https://github.com/kata-containers/agent/blob/master/protocols/grpc/health.proto

The runtime currently makes that call before doing anything else:

- https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L530
- https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L1270

... so we could update the `HealthCheckResponse` to also include the `block_size_bytes` value? It's a bit of a hack maybe but it:

- avoids adding a new gRPC call.
- avoids allowing arbitrary files to be accessed inside the sandbox (I'm not convinced we need that).

**Comment by clarecch** [comment]
@jodh-intel Yep, I will be busy in the following few days, @linzichang will handle this issue instead of me.
